/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include <string.h>
#include "switch_intr.h"

int main(void)
{
    char str[32];
    uint32_t count ;
    SystemInit();
    SwitchInit();
    UartInit(9600);
    UartPuts("HELLO DESD!\r\n");
    DelayMs(1000);

    while(1)
    {	while(SwitchExtiFlag == 0)
		;
sprintf(str,"count=%ld\r\n",count);
DelayMs(1000);

    UartPuts(str);
    SwitchExtiFlag = 0;
    }
    return 0;
}
